"""Agentic legal deep research contracts and helpers."""
from .models import (
    AuthorityCandidate,
    CitationAudit,
    CitationAuditItem,
    CitationAuditStatus,
    CourtListenerMode,
    DeepResearchRequest,
    ParentheticalWeightPolicy,
    ResearchPacket,
    ResearchPlan,
    ResearchQuestion,
    ResearchRun,
    ResearchStatus,
    ResearchStep,
    ResearchSurface,
    ResearchTaskType,
    SelectedAuthority,
    SourcePolicy,
    StatutoryMaterial,
    TreatmentClassification,
    TreatmentSignal,
    normalize_source_policy,
)
from .packets import packet_to_prompt_block, packet_to_research_basis_markdown
from .orchestrator import run_deep_research
from .verification import audit_citations_against_packet, contains_verbatim_quote

__all__ = [
    "AuthorityCandidate",
    "CitationAudit",
    "CitationAuditItem",
    "CitationAuditStatus",
    "CourtListenerMode",
    "DeepResearchRequest",
    "ParentheticalWeightPolicy",
    "ResearchPacket",
    "ResearchPlan",
    "ResearchQuestion",
    "ResearchRun",
    "ResearchStatus",
    "ResearchStep",
    "ResearchSurface",
    "ResearchTaskType",
    "SelectedAuthority",
    "SourcePolicy",
    "StatutoryMaterial",
    "TreatmentClassification",
    "TreatmentSignal",
    "normalize_source_policy",
    "run_deep_research",
    "audit_citations_against_packet",
    "contains_verbatim_quote",
    "packet_to_prompt_block",
    "packet_to_research_basis_markdown",
]
